version: '3'

services:
  mgba-web:
    image: nginx:alpine
    container_name: mgba-web
    ports:
      - "5586:80"
    volumes:
      - ./:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped

  # 可选：如果需要后端API服务
  # mgba-api:
  #   build: ./api
  #   container_name: mgba-api
  #   ports:
  #     - "5586:8000"
  #   restart: unless-stopped 